remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Awesome Audio-visual Learning]
description: [A curated list of audio-visual learning methods and datasets.]